<section class="flex-container aboutus">
    <div class="donate-border">
        <div class="big-title-admin">
            <h2>The Foundation</h2>
        </div>
        <div>
            <img src="https://images.snapwi.re/8a88/576578a26545fd69087b23c6.w800.jpg" alt=""/>
            <h2>This is a title</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit, nemo omnis dolores magni culpa deleniti a adipisci eos fugit sunt.</p>
        </div>
    </div>
</section>