<div class="flex-container">
  <div class="donate-border">
    <div class="big-title-admin">
      <h2>Donation</h2>
    </div>
    <div class="blockquote-wrapper">
      <div class="blockquote">
        <h3>
          Giving is not just about<span style="color:#ffffff"> making a donation. </span>It is about <span style="color:#ffffff">making a difference.</span>
        </h3>
        <h4>&mdash;Kathy Calvin<br><em>From: Google</em></h4>
      </div>
    </div>
    <div id="donate-button-container">
      <div id="donate-button">
        <form action="https://www.paypal.com/donate" method="post" target="_top">
          <input type="hidden" name="hosted_button_id" value="QPN443ZKKUEPC" />
          <input type="image" src="https://pics.paypal.com/00/s/NmNiNGI2NmEtMTAxYS00YjUxLWJhYjUtYTc3YTRiZjk2NTEx/file.PNG" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
          <img alt="" border="0" src="https://www.paypal.com/en_FR/i/scr/pixel.gif" width="1" height="1" />
        </form>
      </div>
      <div class="bg-test"></div>
    </div>
  </div>
</div>
