<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="The Smiling Kids Foundation">
  <link rel="icon" href="images/favicon.png" type="image/x-png" />
  <title>Smiling Kids Foundation -
    <?= $pageTitle ?>
  </title>
  <meta name="viewport" content="width=device-width , initiale-scale=1">
  <!--<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" type="text/css" />
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css" integrity="sha512-0/rEDduZGrqo4riUlwqyuHDQzp2D1ZCgH/gFIfjMIL5az8so6ZiXyhf1Rg8i6xsjv+z/Ubc4tt1thLigEcu6Ug==" crossorigin="anonymous" referrerpolicy="no-referrer"
  />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer"
  />

</head>

<body>
  <header>
    <!-- <div> div avec un slogan et un boutton donate now  </div> -->
    <!-- LOGO + NAV -->
    <div class="curve">
      <div class="overlay">
        <p class="panier">
          <a href="cart.php"><i class="fa-solid fa-heart fa-beat"></i></a>
        </p>
        <h1>The Smiling Kids foundation</h1>
        <h3>Donate for them smile!</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero nostrum quis, odio veniam itaque ullam debitis qui magnam consequatur ab. Vero nostrum quis, odio veniam itaque ullam debitis qui magnam consequatur ab.</p>
        <div id="donate-button-container">
          <div id="donate-button"></div>
          <script src="https://www.paypalobjects.com/donate/sdk/donate-sdk.js"></script>
          <script>
            PayPal.Donation.Button({
              env: 'production',
              hosted_button_id: 'S5N4KSDHWT4XU',
              image: {
                src: 'https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif',
                alt: 'Donate with PayPal button',
                title: 'PayPal - The safer, easier way to pay online!',
              }
            }).render('#donate-button');
          </script>
        </div>

      </div>
    </div>

    <div class="touch"></div>
    <div class="topnav" id="myTopnav">
      <a href="index.php">Home</a>
      <a href="donation.php">Donate</a>
      <a href="news.php">News</a>
      <a href="contact.php">Contact</a>
      <a href="about-us.php">The Foundation</a>
      <?php if(Session::isConnected() && $_SESSION['auth']): ?>
      <div class="dropdown">
        <button class="dropbtn"><i class="fas fa-user"></i>
                      <i class="fa fa-caret-down"></i>
                    </button>
        <div class="dropdown-content">
          <a href="myprofile.php">My Profile</a>
          <a href="logout.php">Logout</a>
        </div>
      </div>
      <?php else: ?>
      <div class="dropdown">
        <button class="dropbtn">Login
                      <i class="fa fa-caret-down"></i>
                    </button>
        <div class="dropdown-content">
          <a href="login.php">Sign in</a>
          <a href="register.php">New Register</a>
        </div>
      </div>
      <?php endif ; ?>
      <a href="javascript:void(0);" class="icon" onclick="myFunction();setActive();">&#9776;</a>
    </div>

    <?php if(Session::isConnected() && $_SESSION['auth']['role']):  ?>
    <!--NAV ADMIN-->
    <div class="iconbar">
      <div class="icons light-blue">
        <i class="icon ion-md-apps"></i>
        <p><a href="dashboard.php">Home</a></p>
      </div>
      <div class="icons green">
        <i class="icon ion-md-list"></i>
        <p><a href="show-post.php">Articles</a></p>
      </div>
      <div class="icons yellow">
        <i class="icon ion-md-body"></i>
        <p><a href="show-user.php">Users</a></p>
      </div>
      <div class="icons red">
        <i class="icon ion-md-heart"></i>
        <p><a href="donator-list.php">Donator</a></p>
      </div>
      <div class="icons purple">
        <i class="icon ion-md-exit"></i>
        <p><a href="logout.php">Log-Out</a></p>
      </div>
    </div>
    <!--FIN NAV ADMIN-->
    <?php endif ; ?>

    <!--<a href="cart.php#modal2" class="js-modal">Panier</a>-->


  </header>
  <main>
    <!--Nous appelons ici notre contenu pour chaque page.-->

    <?= $pageContent ?>

  </main>

  <footer class="footer-container">
    <div class="footer">
      <div class="footer-heading">
        <h2>About Us</h2>
        <a href="about-us.php">The Foundation</a>
        <a href="">Donate Now!</a>
        <a href="">Join us !</a>
        <a href="">Terms of services</a>
      </div>

      <div class="footer-heading">
        <h2>Contact Us</h2>
        <a href="contact.php">Support</a>
        <a href="">Facebook</a>
        <a href="">Instagram</a>
        <a href="">Twitter</a>
      </div>

      <div class="footer-email-form">
        <h2>Join our newsletter</h2>
        <input type="email" name="mail" id="footer-email" placeholder="Enter your email">
        <input type="submit" value="Sign Up" id="footer-email-btn">
      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="js/main.js"></script>
  <script type="module" src="js/localStorage.js"></script>
  <script type="module" src="js/fetch.js"></script>
  <script type="module" src="js/storage.js"></script>
  <script type="module" src="js/events.js"></script>
  <script type="module" src="js/remove.js"></script>
  <script src="https://js.stripe.com/v3/"></script>
  <script type="module" src="js/scripts_paiement.js"></script>

</body>

</html>
