<!--LOG IN PAGE-->
<div class="wrapper login">
    <div class="form-container">
        <div class="col-left">
            <div class="login-text">
                <h2>Welcome Back</h2>
                <p>Feel free to create your account.<br>It's totally free.</p>
                <a href="register.php" class="btn">Sign Up</a>
            </div>
        </div>

        <div class="col-right">
            <div class="login-form">
                <h2>Login</h2>
                <form action="login.php" method="POST">
                    <p>
                        <label for="mail">Email address<span>*</span></label>
                        <input type="text" name="mail" placeholder="Email" id="mail" required>
                    </p>
                    <p>
                        <label for="password">Password<span>*</span></label>
                        <input type="password" name="password" placeholder="Password" id="password" required>
                    </p>
                    <p>
                        <input type="submit" value="Sign In">
                    </p>
                    <p>
                        <a href="">Forget password?</a>
                    </p>

                </form>
            </div>
        </div>

    </div>
</div>
