<!--REGISTER PAGE-->

<div class="wrapper login">
    <div class="form-container">
        <div class="col-left">
            <div class="login-text">
                <h2>Register new account</h2>
                <p>We need your help<br>Please donate.</p>
                <a href="register.php" class="btn">Donate Now!</a>
            </div>
        </div>

        <div class="col-right">
            <div class="login-form">
                <h2>Login</h2>
                <form action="register.php" method="POST">
                    <p>
                        <label for="firstname">Firstname<span>*</span></label>
                        <input type="text" name="firstname" placeholder="Firstname" id="firstname" required/>
                    </p>
                    <p>
                        <label for="lastname">Lastname<span>*</span></label>
                        <input type="text" name="lastname" placeholder="Lastname" id="lastname" required/>
                    </p>
                    <p>
                        <label for="mail">Email address<span>*</span></label>
                        <input type="text" name="mail" placeholder="Email" id="mail" required>
                    </p>
                    <p>
                        <label for="phone">Phone<span>*</span></label>
                        <input name="phone" type="text" placeholder="phone" id="phone">
                    </p>
                    <p>
                        <label for="address">Address<span>*</span></label>
                        <input name="address" type="text" placeholder="address" id="address">
                    </p>
                    <p>
                        <label for="city">City<span>*</span></label>
                        <input name="city" type="text" placeholder="city" id="city">
                    </p>
                    <p>
                        <label for="zipcode">ZipCode<span>*</span></label>
                        <input name="zipcode" type="text" placeholder="zipcode" id="zipcode">
                    </p>
                    <p>
                        <label for="country">Country<span>*</span></label>
                        <input name="country" type="text" placeholder="country" id="country">
                    </p>
                    <p>
                        <label for="password">Password<span>*</span></label>
                        <input type="password" name="password" placeholder="Password" id="password" required>
                    </p>
                    <p>
                        <input type="submit" value="Sign Up">
                    </p>

                </form>
            </div>
        </div>

    </div>
</div>
